language: php
php:
  - 5.3
  - 5.4
  - 5.5

before_install:
  - tests/before_install.sh

script:
  - cd ../core/apps/web_hooks; phpunit --configuration tests/phpunit.xml
  - php tests/coverage-checker.php clover.xml 75
