language: php
php:
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - CORE_BRANCH=master
  matrix:
  - DB=sqlite

branches:
  only:
    - master
    - stable7

install:
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh web_hooks $CORE_BRANCH $DB
  - cd ../core
  - php occ app:enable web_hooks

script:
  # execute unit tests
  - cd apps/web_hooks/tests;
  - phpunit --configuration phpunit.xml

  # push code coverage to scrutinizer-ci
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml

matrix:
  include:
    - php: 5.4
      env: DB=mysql
    - php: 5.4
      env: DB=pgsql
    - php: 5.4
      env: DB=oracle
    - php: hhvm
      env: DB=sqlite
  allow_failures:
    - php: hhvm
  fast_finish: true
