language: php
php:
  - 5.3
  - 5.4
  - 5.5

before_install:
  - tests/before_install.sh
  - cp tests/core_install.sh ../core/
  - cd ../core; ./core_install.sh sqlite

script:
  - cd ../core/apps/web_hooks/tests; phpunit --configuration phpunit.xml
  - cd ../core/apps/web_hooks/tests; php coverage-checker.php clover.xml 75
  - cp ../core/apps/web_hooks/tests/clover.xml tests
